Added Documentation for Swarm Jobs
docker/docs pull request #12037
Opened 2021-01-04 14:59 UTC by ollypom

### Proposed changes

Swarm Jobs were initially implemented in Docker Engine 20.10, this PR adds the documentation.

https://github.com/moby/moby/pull/40307

2021-01-07 18:48 UTC, usha-mandya commented
Thanks @ollypom. 

@thaJeztah Could you PTAL?

2021-01-12 10:08 UTC, thaJeztah requested changes
Arf. Started reviewing this, but didn't manage to finish (wanted to have another look to see what it looks like with my suggestions, but let me submit what I have so far 😓)

2021-01-18 20:45 UTC, ollypom commented
Thanks @thaJeztah :smile:  I've incorporated your feedback in the latest commit.

2021-07-16 12:19 UTC, Felixoid commented
Is there still something blocking the PR from merge?

2021-08-23 22:54 UTC, DakotaNelson commented
Hey @thaJeztah - hate to bug you but it would be awesome if you were able to take another pass at this. Would help a lot of people (including me!) use this functionality thanks to better docs.

The code was released in early December 2020 but in my searching for how to do this, it took quite a while to realize it's actually supported in swarm natively and just undocumented. ☹️

2022-10-21 12:37 UTC, usha-mandya commented
Close and reopen PR to trigger build checks

2022-11-01 10:09 UTC, hertzg commented
@usha-mandya Seems like there's some MDL issues and a broken link (htmlproffer) reported by the checks

2022-12-27 02:00 UTC, closed without merging

2024-12-24 06:03 UTC, guoard commented
@thaJeztah PTAL