Update github-actions.md
docker/docs pull request #15733
Opened 2022-09-24 05:08 UTC by akramsystems

This step was missing from the optimize docker build using cache, without it the build fails with the following error message

```
Error: buildx failed with: ERROR: cache export feature is currently not supported for docker driver. Please switch to a different driver (eg. "docker buildx create --use")
```

### Proposed changes

### Related issues (optional)

2022-09-27 11:06 UTC, crazy-max requested changes

2022-09-27 11:06 UTC, crazy-max commented on ci-cd/github-actions.md
> +        uses: docker/setup-buildx-action@v1
```suggestion
        uses: docker/setup-buildx-action@v2
```

2022-10-16 05:32 UTC, akramsystems commented
@crazy-max updated sorry for the delay

2022-10-20 18:44 UTC, akramsystems reviewed
applied changes requested

2022-10-20 19:02 UTC, crazy-max commented on ci-cd/github-actions.md
> +
* Why downgrading to `docker/login-action@v1`?
* `-` missing for `Build and push`
* Please keep the layout as it is and just add the `Set up Docker Buildx` step in your changes.

2023-03-15 02:00 UTC, closed without merging