build: buildkit resource limiting
docker/docs pull request #16324
Opened 2022-12-12 10:31 UTC by crazy-max

moved from https://github.com/docker/buildx/blob/master/docs/guides/resource-limiting.md

Signed-off-by: CrazyMax <crazy-max@users.noreply.github.com>

2022-12-12 11:03 UTC, dvdksn requested changes

2022-12-12 11:03 UTC, dvdksn commented on build/buildkit/configure.md
> +(image config retrieval) to enhance the overall build time.
Is this a fair rewording?

```suggestion
TCP connections are limited to 4 simultaneous connections per registry for pulling
and pushing images, plus one additional connection dedicated to metadata requests. 
This connection limit prevents your build from getting stuck while pulling images.
The dedicated metadata connection helps reduce the overall build time.
```

2022-12-12 12:44 UTC, jedevc commented
LGTM, once @dvdksn's comments are resolved :+1:

2022-12-13 16:35 UTC, dvdksn approved these changes

2022-12-14 05:33 UTC, merged