Document new bake matrix builds
docker/docs pull request #17041
Opened 2023-04-05 10:56 UTC by jedevc

Document new matrix build features added in https://github.com/docker/buildx/pull/1690. Marking as draft until ready to release.

2023-04-05 11:35 UTC, dvdksn requested changes

2023-04-05 11:35 UTC, dvdksn commented on build/bake/configuring-build.md
> +generated target **must** have a unique name -- these names should be manually
```suggestion
generated target **must** have a unique name. These names should be manually
```

2023-04-05 11:35 UTC, dvdksn commented on build/bake/configuring-build.md
> +You can use the matrix feature to easily define multiple targets that are
```suggestion
You can use the matrix feature to define multiple targets that are
```

2023-05-31 11:06 UTC, jedevc commented
Replaced by https://github.com/docker/buildx/pull/1791.

2023-05-31 11:06 UTC, closed without merging