Add details on Docker Scout internals
docker/docs pull request #17191
Opened 2023-04-26 12:44 UTC by ChrisChinchilla

### Proposed changes

This PR adds details on Docker Scouts advisor database and how it matches.

2023-04-26 14:02 UTC, jonnyrobots requested changes

2023-04-26 14:09 UTC, ChrisChinchilla commented on _data/toc.yaml
> +      title: How Docker Scout works
But also happy to just keep it to this too

2023-04-26 14:10 UTC, ChrisChinchilla commented on _data/toc.yaml
> +      title: How Docker Scout works
```suggestion
      title: Advisory Database
```

2023-04-27 09:36 UTC, jonnyrobots approved these changes
lgtm

2023-04-27 09:36 UTC, jonnyrobots approved these changes

2023-04-27 10:54 UTC, aevesdocker approved these changes

2023-04-27 10:57 UTC, merged