Move Scout package ecosystem section
docker/docs pull request #17207
Opened 2023-04-28 10:57 UTC by ChrisChinchilla

### Proposed changes

Consolidates package ecosystem into newer details page.

2023-04-28 11:10 UTC, aevesdocker submitted a review, later dismissed

2023-04-28 13:31 UTC, dvdksn approved these changes

2023-05-02 12:45 UTC, jonnyrobots commented on scout/advisory-db-sources.md
> +And the following package ecosystems:
Or perhaps it's simply a new section heading?
Eg. "Package ecosystems supported by the Docker Scout Advisory Database"

2023-05-02 15:52 UTC, ChrisChinchilla commented on scout/advisory-db-sources.md
> +And the following package ecosystems:
@jonnyrobots OK, I misread the earlier discussions. Done and for now moved to the bottom as it felt "disruptive" to have it in the existing sections, but can find a way to move it up if you think that's better.

2023-05-03 11:58 UTC, dvdksn commented on scout/advisory-db-sources.md
> +- `deb` (Debian Linux and derivatives)
I think we forgot this little fella :)

2023-05-03 12:08 UTC, ChrisChinchilla commented on scout/advisory-db-sources.md
> +- `deb` (Debian Linux and derivatives)
Debian deserves it's own place :)

2023-05-03 12:12 UTC, dvdksn submitted a review, later dismissed
LGTM - please squash!

2023-05-03 21:11 UTC, jonnyrobots requested changes
Not strictly related to this PR, but in the same file (`advisory-db-sources.md`); can we replace the word scanning, please?

> Docker Scout is ideal for ~scanning~ images in Docker Desktop and Docker Hub
to
> Docker Scout is ideal for *analysing* images in Docker Desktop and Docker Hub

2023-05-04 07:59 UTC, ChrisChinchilla commented
@jonnyrobots It's a good catch.

2023-05-09 09:21 UTC, aevesdocker approved these changes

2023-05-09 09:24 UTC, merged