Fix "scope" default value for GHA cache options
docker/docs pull request #17462
Opened 2023-06-01 23:17 UTC by james-warren0

Update the `cache-to` and `cache-from` `scope` config value to the correct default of `buildkit`.

### Proposed changes

The documentation for the GitHub Action cache is incorrect in listing that the branch name is the default scope value. The correct value is `buildkit`, which is also listed as the default value in the buildkit docs [here](https://github.com/moby/buildkit#github-actions-cache-experimental).

### Related issues (optional)

N/A

2023-06-02 04:21 UTC, dvdksn commented
@crazy-max could you ptal?

2023-08-24 11:27 UTC, crazy-max submitted a review, later dismissed

2023-08-24 11:27 UTC, crazy-max commented
Arg needs rebase :sweat_smile:

2023-08-24 11:28 UTC, crazy-max requested changes
Needs rebase :pray:

2023-11-22 08:14 UTC, dvdksn commented
Fixed in 17eb61acf31656c09751fa5bc4b4cbd60030ed90

2023-11-22 08:14 UTC, closed without merging