appending cmd tab in trying out bind mounts section to work Closes #18242
docker/docs pull request #18243
Opened 2023-09-20 15:06 UTC by arminshfatemi

### Proposed changes

### Related issues (optional)

2023-09-29 19:06 UTC, craig-osterhout requested changes
Thanks for adding the command.
Commented on a few style nits and a numbering issue.

2023-09-29 19:06 UTC, craig-osterhout commented on content/get-started/06_bind_mounts.md
>     Run this command in PowerShell.
Can probably remove this line since it becomes redundant with the tab.
```suggestion

```

2023-09-30 12:25 UTC, arminshfatemi reviewed
looks like this line was ok

2023-09-30 12:25 UTC, arminshfatemi reviewed
looks like dont need to change

2023-09-30 12:25 UTC, arminshfatemi reviewed
looks like it didnt need to change

2023-10-05 15:35 UTC, craig-osterhout commented on content/get-started/06_bind_mounts.md
> +   {{< tab name="Windows-CMD" >}}
```suggestion
   {{< tab name="Windows (CMD)" >}}
```

2023-10-05 15:36 UTC, craig-osterhout approved these changes
Thank you. LGTM

2023-10-05 15:39 UTC, merged