Engdocs 1871
docker/docs pull request #18780
Opened 2023-11-24 16:00 UTC by aevesdocker

Closes https://github.com/docker/docs/issues/18750
Closes https://github.com/docker/docs/issues/18666

2023-11-24 19:46 UTC, dvdksn requested changes
I have one specific comment related to the change, which is about file lookup order. The current change doesn't address the fact that you can have multiple compose filenames and they take presedence in different ways.

Then I had several comments on things unrelated to these changes but that I noticed in passing.

2023-11-24 19:46 UTC, dvdksn commented on content/compose/reference/_index.md
>        --compatibility              Run compose in backward compatibility mode
The `--dry-run` flag is missing

2023-11-24 19:46 UTC, dvdksn commented on content/compose/reference/_index.md
>        --profile stringArray        Specify a profile to enable
The `--progress` flag is missing

2023-11-24 19:46 UTC, dvdksn commented on content/compose/reference/_index.md
> +      --env-file stringArray       Specify an alternate environment file
This period is there in the cobra help string so we probably want to update it in the code as well

2023-11-24 19:46 UTC, dvdksn commented on content/compose/reference/_index.md
unrelated to the changes here, but we could probably use an example here for reading the compose file from stdin with a heredoc

2023-11-24 19:46 UTC, dvdksn commented on content/compose/reference/_index.md
>  configuration.
Not related to this change, but this description is inaccurate. Some fields are merged, not overridden. Labels, for example:

```yaml
# compose.yaml
services:
  webapp:
    build:
      context: .
      labels: 
        com.example.foo: "foo"
```

```yaml
# overrides.yaml
services:
  webapp:
    build:
      context: .
      labels: 
        com.example.name: "Alice"
```

```console
$ docker compose -f compose.yaml -f overrides.yaml build
$ docker image inspect compose-webapp --format json | jq '.[].Config.Labels'
{
  "com.docker.compose.project": "compose",
  "com.docker.compose.service": "webapp",
  "com.docker.compose.version": "2.23.0",
  "com.example.foo": "foo",
  "com.example.name": "Alice"
}
```

`buildx bake` has similar behavior and I've described how duplicate fields either merge with or override previous definitions in the bake file reference, see here: https://docs.docker.com/build/bake/reference/#file-format

2023-11-24 19:46 UTC, dvdksn commented on content/compose/reference/_index.md
> +at least the `compose.yml` file. If both files are present on the same
Both `docker-compose.yml` and `compose.yml` and corresponding override files are supported. Compose has some logic for deciding the lookup order of these files, which is what I think #18666 is asking for. How do these variants interact?

Again the bake file has a similar behavior so you can take a look at how I did it there: https://docs.docker.com/build/bake/reference/#file-format

2023-12-04 11:32 UTC, aevesdocker commented
Thanks @dvdksn. It's on my radar that this page needs some TLC. I've addressed your main blocking comment. The rest I'll do in a follow-up

2023-12-05 18:59 UTC, dvdksn approved these changes

2023-12-06 09:57 UTC, merged