engine: 26.0.0 release notes
docker/docs pull request #19648
Opened 2024-03-19 09:06 UTC by vvoland

Engine release notes (draft, but no changes are expected).

## Reviews

- [ ] Technical review
- [ ] Editorial review
- [ ] Product review

2024-03-19 09:27 UTC, sam-thibault requested changes

2024-03-19 09:27 UTC, sam-thibault commented on hugo.yaml
> +  buildkit_version: "0.13.0"
This should be `0.13.1`, right?

2024-03-19 09:35 UTC, vvoland commented on hugo.yaml
> +  buildkit_version: "0.13.0"
Yes, fixed, thanks!

2024-03-20 03:18 UTC, dvdksn commented on content/engine/release-notes/26.0.md
> +- cli/command: remove deprecated `DockerCliOption`, `InitializeOpt`[docker/cli#4810](https://github.com/docker/cli/pull/4810)
We don't normally include changes to Go modules. Do we want to keep these? @thaJeztah

2024-03-20 20:15 UTC, neersighted requested changes
I've carried this at https://github.com/docker/docs/pull/19658 since we ended up with some differences in the final upstream release notes; I'll also try to bring the unresolved discussions over.

2024-03-20 20:16 UTC, closed without merging