config: Add new [program] sections and example scripts to supervisord.conf
docker/docs pull request #19881
Opened 2024-04-25 14:44 UTC by elegantcoder

## Description

I believe the current `supervisord.conf` in the documentation is not suitable for demonstrating a multi-service container. It does not explicitly mention the previously introduced `my_first_script` and `my_second_script`, which reduces its relevance to multi-service container configurations.
To more easily achieve the desired outcome, I have also added examples of `my_first_script` and `my_second_script` to the documentation. 

## Related issues or tickets

## Reviews

- [ ] Technical review
- [ ] Editorial review
- [ ] Product review

2024-07-30 02:50 UTC, offensive-vk requested changes
Any other examples other than sleep function?

2024-07-30 04:09 UTC, elegantcoder commented
@offensive-vk  For a simple example, I think the sleep function demonstrates well. If you have a better idea, I'd love to hear it.

2024-08-01 08:01 UTC, elegantcoder commented
/remove-lifecycle stale

2024-08-07 08:41 UTC, offensive-vk approved these changes
It seems okay now. Good job

2024-08-07 09:00 UTC, offensive-vk commented
Hey @dvdksn , can you please take a look here?
Thank you 🙌

2024-08-07 09:28 UTC, dvdksn reviewed
LGTM. One suggestion to the Dockerfile example: we can set chmod and copy both files in one go

2024-08-07 09:28 UTC, dvdksn commented on content/config/containers/multi-service_container.md
> +RUN chmod +x my_first_process my_second_process
```suggestion
COPY --chmod=755 my_first_process my_second_process .
```

2024-08-07 12:25 UTC, dvdksn submitted a review, later dismissed

2024-08-28 18:44 UTC, elegantcoder commented
Hey, I saw the PR got approved! Just checking if you’re planning to merge it soon, or if there's anything else needed?

2024-08-29 16:26 UTC, elegantcoder commented
I'm gonna close this pull request. When I first discovered a part where I could contribute to this document, I was happy, but seeing how slow your processing has been, I'm not feeling great about it now.

2024-08-29 16:26 UTC, closed without merging