Update 05_persisting_data.md
docker/docs pull request #19956
Opened 2024-05-03 07:39 UTC by HarshPatel270698

Correcting spelling mistake and separating console of command and op.

## Description

## Related issues or tickets

## Reviews

- [ ] Technical review
- [ ] Editorial review
- [ ] Product review

2024-05-03 07:42 UTC, HarshPatel270698 commented
Can anyone review this? The console block is copying output with the command.
Thanks

2024-05-06 15:09 UTC, craig-osterhout requested changes
Thanks @HarshPatel270698. 
One small nit to add punctuation, otherwise LGTM.

2024-05-06 15:09 UTC, craig-osterhout commented on content/get-started/05_persisting_data.md
> +You should see output like the following
```suggestion
You should see output like the following:
```

2024-05-23 22:12 UTC, craig-osterhout approved these changes

2024-05-23 22:29 UTC, merged