(Fixed) Incorrect command to remove old versions docker(centos)
docker/docs pull request #20506
Opened 2024-07-31 05:36 UTC by iamAyushChamoli

Fixes #20460

## Description

Updated the command to remove old versions docker from `sudo yum remove docker` to `sudo yum remove docker-ce`

## Related issues or tickets

Issue #20460 

## Reviews

- [ ] Technical review
- [ ] Editorial review
- [ ] Product review

2024-08-01 04:04 UTC, dvdksn commented
This refers to old names of Docker that aren't used anymore. We could make that clearer, I guess.

2024-08-06 21:39 UTC, thaJeztah requested changes

2024-08-06 21:39 UTC, thaJeztah commented on content/engine/install/centos.md
> +$ sudo yum remove docker-ce \
I don't think this is correct; the intent here was to uninstall the package named `docker` (if installed), which is an older name of a package that shipped docker. The intent is not to uninstall a  previous install of the `docker-ce` package (which is the current name of the package)

2024-08-06 21:40 UTC, thaJeztah commented
Oh! I had this review pending and forgot to submit it, but I see @dvdksn already left a similar comment 🙈

2024-08-18 11:09 UTC, closed without merging