Add example that shows the stated "default" settings in json
docker/docs pull request #21596
Opened 2024-12-09 19:04 UTC by rrauenza

(also fix an errant . )

## Description

Add an example that matches the stated defaults.

It isn't obvious from current docs that json requires only a single '=' sign.  Also the "type" settings all need to be in one string, so this gives an example showing that.

2024-12-09 19:12 UTC, rrauenza commented
.... I see the lint error, but I'm also not convinced this feature actually works.   

I'm gonna open a bug to clarify.

2024-12-10 09:30 UTC, dvdksn requested changes
Thank you, but I would like to wait with this change. The buildkitd gc config has changed in v0.18, and so has the defaults. While that version doesn't yet ship with Docker Engine, it soon will and I'll need to make space for both the old and the new config format (incl. buildkitd and daemon.json)

2024-12-10 18:23 UTC, rrauenza commented
So that would also address https://github.com/moby/buildkit/issues/5581 ?  With the == / = behavior?

2024-12-11 08:29 UTC, dvdksn commented
Hmm, no I don't think the filters are affected by the new config options. KeepBytes was replaced by three, more configurable options in v0.17. GC config via daemon.json does not yet use all of these new options. But I don't believe filtering was changed, it only gave new ways to define the GC threshold (min reserved bytes, maximum used space, min free disk space)

2025-04-10 02:00 UTC, closed without merging