documentation for alternative credential_spec mode
docker/docs pull request #7006
Opened 2018-07-10 17:11 UTC by jrdbarnes

### Proposed changes

credential_spec only works in swarm mode, provide documentation to use security_opt when not in swarm mode.

### Related issues (optional)

https://github.com/docker/compose/issues/5488

2019-02-22 13:39 UTC, L-Hudson commented
@axeal PTAL, thanks! Or, let me know if someone else should be reviewing.

2019-02-28 13:50 UTC, L-Hudson commented
@darwin-traver, PTAL? thanks.

2019-05-22 18:50 UTC, bermudezmt commented
@ulyssessouza can you PTAL? Thanks!

2021-09-10 14:35 UTC, macoMarv86 approved these changes
good for issue

2021-09-10 15:08 UTC, macoMarv86 requested changes
good for issue

2022-10-13 16:09 UTC, closed without merging